GET http://localhost:3000/api/posts

###

POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title":"제목4",
    "content":"hello3"
}

###

PUT http://localhost:3000/api/posts/2
Content-Type: application/json

{
    "id": 2,
    "title": "식물에 물 주기3"
}

###

DELETE http://localhost:3000/api/posts/5